create table if not exists product_raw
(
    id                 bigint generated by default as identity
        primary key,
    source             varchar(30)  not null,
    type               varchar(20)  not null,
    external_id        varchar(150) not null,
    content_hash       varchar(64)  not null,
    raw_json           text         not null,
    last_seen_at       timestamptz    not null,
    normalized_at      timestamptz,
    normalizer_version integer,
    created_at         timestamptz    not null,
    updated_at         timestamptz,
    constraint uk_product_raw_source_external_id
        unique (source, external_id)
);


create index if not exists idx_product_raw_source
    on product_raw (source);

create index if not exists idx_product_raw_normalized
    on product_raw (source, normalized_at);

CREATE TABLE IF NOT EXISTS product_source (
                                id BIGSERIAL PRIMARY KEY,
                                code VARCHAR(20) NOT NULL UNIQUE,
                                name VARCHAR(50) NOT NULL
);

INSERT INTO product_source (code, name) VALUES
                                            ('FSS', '금융감독원'),
                                            ('ONTONG', '온통청년')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

CREATE TABLE IF NOT EXISTS provider (
                          id BIGSERIAL PRIMARY KEY,
                          source_id BIGINT NOT NULL REFERENCES product_source(id),
                          code VARCHAR(100),
                          name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
                         id BIGSERIAL PRIMARY KEY,
                         source_id BIGINT NOT NULL REFERENCES product_source(id),
                         type VARCHAR(20) NOT NULL,
                         product_code VARCHAR(100),
                         product_name VARCHAR(200) NOT NULL,
                         content TEXT,
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_properties (
                                    id BIGSERIAL PRIMARY KEY,
                                    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
                                    provider_id BIGINT NOT NULL REFERENCES provider(id),
                                    base_rate DECIMAL(5,2),
                                    max_rate DECIMAL(5,2),
                                    gov_contribution_rate DECIMAL(5,2),
                                    min_monthly_limit BIGINT,
                                    max_monthly_limit BIGINT,
                                    min_age INT,
                                    max_age INT,
                                    earn_max_amt BIGINT,
                                    earn_percent INT,
                                    min_tenure_months INT,
                                    requires_homeless BOOLEAN NOT NULL DEFAULT FALSE,
                                    requires_householder BOOLEAN NOT NULL DEFAULT FALSE,
                                    is_joinable BOOLEAN NOT NULL DEFAULT TRUE,
                                    apply_url VARCHAR(500),
                                    intr_rate_type VARCHAR(30),
                                    save_trm INT
);

CREATE TABLE IF NOT EXISTS product_property_keyword (
                                 id BIGSERIAL PRIMARY KEY,
                                 product_property_id BIGINT NOT NULL REFERENCES product_properties(id) ON DELETE CASCADE,
                                 keyword_code VARCHAR(50) NOT NULL
);

-- SELECT setval(pg_get_serial_sequence('product_raw', 'id'), COALESCE((SELECT MAX(id) FROM product_raw), 1), (SELECT MAX(id) FROM product_raw) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('product_source', 'id'), COALESCE((SELECT MAX(id) FROM product_source), 1), (SELECT MAX(id) FROM product_source) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('provider', 'id'), COALESCE((SELECT MAX(id) FROM provider), 1), (SELECT MAX(id) FROM provider) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('product', 'id'), COALESCE((SELECT MAX(id) FROM product), 1), (SELECT MAX(id) FROM product) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('product_properties', 'id'), COALESCE((SELECT MAX(id) FROM product_properties), 1), (SELECT MAX(id) FROM product_properties) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('product_property_keyword', 'id'), COALESCE((SELECT MAX(id) FROM product_property_keyword), 1), (SELECT MAX(id) FROM product_property_keyword) IS NOT NULL);
