create table if not exists product_raw
(
    id                 bigint generated by default as identity
        primary key,
    source             varchar(30)  not null,
    external_id        varchar(150) not null,
    content_hash       varchar(64)  not null,
    raw_json           text         not null,
    last_seen_at       timestamp    not null,
    normalized_at      timestamp,
    normalizer_version integer,
    created_at         timestamp    not null,
    updated_at         timestamp,
    constraint uk_product_raw_source_external_id
        unique (source, external_id)
);


create index if not exists idx_product_raw_source
    on product_raw (source);

create index if not exists idx_product_raw_normalized
    on product_raw (source, normalized_at);
