create table if not exists product_raw
(
    id                 bigint generated by default as identity
        primary key,
    source             varchar(30)  not null,
    type               varchar(20)  not null,
    external_id        varchar(150) not null,
    content_hash       varchar(64)  not null,
    raw_json           text         not null,
    last_seen_at       timestamptz    not null,
    normalized_at      timestamptz,
    normalizer_version integer,
    created_at         timestamptz    not null,
    updated_at         timestamptz,
    constraint uk_product_raw_source_external_id
        unique (source, external_id)
);


create index if not exists idx_product_raw_source
    on product_raw (source);

create index if not exists idx_product_raw_normalized
    on product_raw (source, normalized_at);

CREATE TABLE IF NOT EXISTS product_source (
                                id BIGSERIAL PRIMARY KEY,
                                code VARCHAR(20) NOT NULL UNIQUE,
                                name VARCHAR(50) NOT NULL
);

INSERT INTO product_source (code, name) VALUES
                                            ('FSS', '금융감독원'),
                                            ('ONTONG', '온통청년')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

CREATE TABLE IF NOT EXISTS provider (
                          id BIGSERIAL PRIMARY KEY,
                          source_id BIGINT NOT NULL REFERENCES product_source(id),
                          code VARCHAR(100),
                          name VARCHAR(100) NOT NULL,
                          apply_url VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS product (
                         id BIGSERIAL PRIMARY KEY,
                         source_id BIGINT NOT NULL REFERENCES product_source(id),
                         type VARCHAR(20) NOT NULL,
                         product_code VARCHAR(100),
                         product_name VARCHAR(200) NOT NULL,
                         content TEXT,
                         content_summary TEXT,
                         join_method TEXT,
                         eligibility_text TEXT,
                         caution_text TEXT,
                         recruitment_period TEXT,
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_properties (
                                    id BIGSERIAL PRIMARY KEY,
                                    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
                                    provider_id BIGINT NOT NULL REFERENCES provider(id),
                                    base_rate DECIMAL(5,2),
                                    max_rate DECIMAL(5,2),
                                    gov_contribution_rate DECIMAL(5,2),
                                    gov_contribution_type VARCHAR(30),
                                    gov_matching_ratio DECIMAL(8,4),
                                    gov_monthly_fixed_contribution BIGINT,
                                    gov_contribution_period_months INT,
                                    exclude_from_rate_comparison BOOLEAN NOT NULL DEFAULT FALSE,
                                    min_monthly_limit BIGINT,
                                    max_monthly_limit BIGINT,
                                    min_age INT,
                                    max_age INT,
                                    allows_military_age_extension BOOLEAN NOT NULL DEFAULT FALSE,
                                    military_max_age INT,
                                    earn_max_amt BIGINT,
                                    earn_percent INT,
                                    min_tenure_months INT,
                                    requires_homeless BOOLEAN NOT NULL DEFAULT FALSE,
                                    requires_householder BOOLEAN NOT NULL DEFAULT FALSE,
                                    is_joinable BOOLEAN NOT NULL DEFAULT TRUE,
                                    apply_url VARCHAR(500),
                                    intr_rate_type VARCHAR(30),
                                    rsrv_type VARCHAR(30),
                                    save_trm INT
);

CREATE TABLE IF NOT EXISTS product_property_keyword (
                                 id BIGSERIAL PRIMARY KEY,
                                 product_property_id BIGINT NOT NULL REFERENCES product_properties(id) ON DELETE CASCADE,
                                 keyword_code VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS product_property_required_keyword (
                                 id BIGSERIAL PRIMARY KEY,
                                 product_property_id BIGINT NOT NULL REFERENCES product_properties(id) ON DELETE CASCADE,
                                 keyword_code VARCHAR(50) NOT NULL,
                                 effect VARCHAR(20) NOT NULL DEFAULT 'REQUIRE',
                                 confidence VARCHAR(20) NOT NULL DEFAULT 'HIGH'
);

CREATE TABLE IF NOT EXISTS product_preferential_rates (
                                 id BIGSERIAL PRIMARY KEY,
                                 product_property_id BIGINT NOT NULL REFERENCES product_properties(id) ON DELETE CASCADE,
                                 keyword_code VARCHAR(50) NOT NULL,
                                 rate DECIMAL(5,2) NOT NULL,
                                 description TEXT,
                                 min_age INT,
                                 max_age INT
);

CREATE TABLE IF NOT EXISTS llm_enrichment_cache (
                                  id BIGSERIAL PRIMARY KEY,
                                  source VARCHAR(30) NOT NULL,
                                  external_id VARCHAR(150) NOT NULL,
                                  content_hash VARCHAR(64) NOT NULL,
                                  provider VARCHAR(30) NOT NULL,
                                  model VARCHAR(100) NOT NULL,
                                  prompt_version INT NOT NULL,
                                  schema_version INT NOT NULL,
                                  request_hash VARCHAR(64) NOT NULL,
                                  status VARCHAR(20) NOT NULL,
                                  response_json TEXT,
                                  error_message TEXT,
                                  failure_count INT NOT NULL DEFAULT 0,
                                  last_failed_at TIMESTAMP WITH TIME ZONE,
                                  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  CONSTRAINT uk_llm_enrichment_cache_key UNIQUE (
                                      source,
                                      external_id,
                                      content_hash,
                                      provider,
                                      model,
                                      prompt_version,
                                      schema_version
                                  )
);

ALTER TABLE IF EXISTS llm_enrichment_cache
    ADD COLUMN IF NOT EXISTS failure_count INT NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS llm_enrichment_cache
    ADD COLUMN IF NOT EXISTS last_failed_at TIMESTAMP WITH TIME ZONE;

-- SELECT setval(pg_get_serial_sequence('product_raw', 'id'), COALESCE((SELECT MAX(id) FROM product_raw), 1), (SELECT MAX(id) FROM product_raw) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('product_source', 'id'), COALESCE((SELECT MAX(id) FROM product_source), 1), (SELECT MAX(id) FROM product_source) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('provider', 'id'), COALESCE((SELECT MAX(id) FROM provider), 1), (SELECT MAX(id) FROM provider) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('product', 'id'), COALESCE((SELECT MAX(id) FROM product), 1), (SELECT MAX(id) FROM product) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('product_properties', 'id'), COALESCE((SELECT MAX(id) FROM product_properties), 1), (SELECT MAX(id) FROM product_properties) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('product_property_keyword', 'id'), COALESCE((SELECT MAX(id) FROM product_property_keyword), 1), (SELECT MAX(id) FROM product_property_keyword) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('product_property_required_keyword', 'id'), COALESCE((SELECT MAX(id) FROM product_property_required_keyword), 1), (SELECT MAX(id) FROM product_property_required_keyword) IS NOT NULL);
-- SELECT setval(pg_get_serial_sequence('product_preferential_rates', 'id'), COALESCE((SELECT MAX(id) FROM product_preferential_rates), 1), (SELECT MAX(id) FROM product_preferential_rates) IS NOT NULL);
