CREATE TABLE IF NOT EXISTS product_raw
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source             VARCHAR(30) NOT NULL,
    type               VARCHAR(20) NOT NULL,
    external_id        VARCHAR(150) NOT NULL,
    content_hash       VARCHAR(64) NOT NULL,
    raw_json           TEXT NOT NULL,
    last_seen_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    normalized_at      TIMESTAMP WITH TIME ZONE,
    normalizer_version INTEGER,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_product_raw_source_external_id UNIQUE (source, external_id)
);

CREATE INDEX IF NOT EXISTS idx_product_raw_source
    ON product_raw (source);

CREATE INDEX IF NOT EXISTS idx_product_raw_normalized
    ON product_raw (source, normalized_at);

CREATE TABLE IF NOT EXISTS llm_enrichment_cache
(
    id              BIGSERIAL PRIMARY KEY,
    source          VARCHAR(30) NOT NULL,
    external_id     VARCHAR(150) NOT NULL,
    content_hash    VARCHAR(64) NOT NULL,
    provider        VARCHAR(30) NOT NULL,
    model           VARCHAR(100) NOT NULL,
    prompt_version  INT NOT NULL,
    schema_version  INT NOT NULL,
    request_hash    VARCHAR(64) NOT NULL,
    status          VARCHAR(20) NOT NULL,
    response_json   TEXT,
    error_message   TEXT,
    failure_count   INT NOT NULL DEFAULT 0,
    last_failed_at  TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_llm_enrichment_cache_key UNIQUE (
        source,
        external_id,
        content_hash,
        provider,
        model,
        prompt_version,
        schema_version
    )
);
