spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations:
        - classpath:data.sql
        - classpath:seed/01-providers.sql
        - classpath:seed/02-products.sql
        - classpath:seed/03-product-properties.sql
        - classpath:seed/04-product-keywords.sql
        - classpath:seed/05-product-required-keywords.sql
        - classpath:seed/06-product-preferential-rates.sql
